{
 "title": "Usage",
 "time": { "from": "2023-05-31T15:48:22.538Z", "to": "2023-05-31T16:14:59.722Z" },
 "templating": {
  "list": [
   { "name": "Application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk free - bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "disk_free_bytes{application=\"$Application\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage alerts",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$Application\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}