{
 "title": "JVM",
 "time": { "from": "2023-06-02T16:44:59.990Z", "to": "2023-06-02T16:48:45.431Z" },
 "panels": [
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Live Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"Movie Recommendation Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads Deamon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{application=\"Movie Recommendation Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Max GC Pause",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{cause=\"Metadata GC Threshold\", application=\"Movie Recommendation Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage after GC",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_usage_after_gc_percent{application=\"Movie Recommendation Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_overhead_percent{application=\"Movie Recommendation Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Buffer Memory Used - bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"Movie Recommendation Service\", id=\"direct\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer total capacity - bytes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"Movie Recommendation Service\", id=\"direct\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}